### ISSUE TITLE
Projekttag 2023 - Feature Tracking

### ISSUE THREAD

**Issue by m4xxed** [uni-bremen-agst/SEE#573]
We aim to integrate the following capabilities until Projekttag 2023 (21-04-2023)

- [x] multi-user capability including VR
- [x]  AutoHand
- [x] architecture verification
- [x] visualize clones
- [x] move nodes (desktop only)
- [x] select edges
- [x] audiochat for multi-user scenario (TESTING REQUIRED)
- [x] synchronized body movements (in multi user scenario VR + desktop)
- [ ] source code documentation windows
- [x] mirror
- [x] VR with facial tracker
- [x] runtime configuration

**Comment by falko17** [comment]
@koschke Should this still be kept open? The only non-checked part here seems to be "source code documentation windows," which is technically an LSP feature (albeit as a popup instead of its own window) that has been implemented as part of #686.

**Comment by koschke** [comment]
It can be closed.  Thanks for the hint. I am closing it.
